### ISSUE TITLE
after installing the following error

### ISSUE THREAD

**Issue by isaack0815** [fancoder/cryptonote-universal-pool#106]
Hello,
have with me on a fresh Ubuntu 16.04 server monero installed. now wanted to install this pool with it and only get errors after installation.

this is my config.json
 {

    "coin": "Monero",
    "symbol": "XMR",
    "coinUnits": 100000000,
    "coinDifficultyTarget": 120,
    "logging": {
        "files": {
            "level": "info",
            "directory": "logs",
            "flushInterval": 5
        },
        "console": {
            "level": "info",
            "colors": true
        }
    },

    "poolServer": {
        "enabled": true,
        "clusterForks": "auto",
        "poolAddress": "44oWW9PV8vyauZjkmL7tGLSEnDdgGMVFw44xhxkLxyAUFJmACWthKJXe3M4SSEgxzpdMWs9MQZhx8UvzbPWC8yKgSbjPiSr","addressBase58Prefix": 18,
        "blockRefreshInterval": 1000,
        "minerTimeout": 900,
        "ports": [
            {
                "port": 3333,
                "difficulty": 100,
                "desc": "Low end hardware"
            },
            {
                "port": 5555,
                "difficulty": 2000,
                "desc": "Mid range hardware"
            },
            {
                "port": 7777,
                "difficulty": 10000,
                "desc": "High end hardware"
            },
            {
                "port": 8888,
                "difficulty": 10000,
                "desc": "Hidden port",
                "hidden": true
            }
        ],
        "varDiff": {
            "minDiff": 2,
            "maxDiff": 100000,
            "targetTime": 100,
            "retargetTime": 30,
            "variancePercent": 30,
            "maxJump": 100
        },
        "fixedDiff": {
            "enabled": true,
            "addressSeparator": "."
        },
        "shareTrust": {
            "enabled": true,`       "shareTrust": {
            "enabled": true,
            "min": 10,
            "stepDown": 3,
            "threshold": 10,
            "penalty": 30
        },
        "banning": {
            "enabled": true,
            "time": 600,
            "invalidPercent": 25,
            "checkThreshold": 30
        }
    },

    "payments": {
        "enabled": true,
        "interval": 600,
        "maxAddresses": 50,
        "mixin": 3,
        "transferFee": 5000,
        "minPayment": 30000000,
        "denomination": 1000
    },

    "blockUnlocker": {
        "enabled": true,
        "interval": 30,
        "depth": 60,
        "poolFee": 1,
        "devDonation": 0.2,
        "coreDevDonation": 0.2,
        "extraFeaturesDevDonation":0.1
    },

    "api": {
        "enabled": true,
        "hashrateWindow": 600,
        "updateInterval": 5,
        "port": 8117,
        "blocks": 30,
        "payments": 30,
        "password": "seceret_pass"
    },

    "daemon": {
        "host": "127.0.0.1",
        "port": 18081
    },

    "wallet": {
        "host": "127.0.0.1",
        "port": 8082
    },

    "redis": {
        "host": "127.0.0.1",
        "port": 6379
    },

    "monitoring": {
        "daemon": {    "monitoring": {
        "daemon": {
            "checkInterval": 60,
            "rpcMethod": "getblockcount"
        },
        "wallet": {
            "checkInterval": 60,
            "rpcMethod": "getbalance"
        }
    },

    "charts": {
        "pool": {
            "hashrate": {
                "enabled": true,
                "updateInterval": 60,
                "stepInterval": 1800,
                "maximumPeriod": 86400
            },
            "workers": {
                "enabled": true,
                "updateInterval": 60,
                "stepInterval": 1800,
                "maximumPeriod": 86400
            },
            "difficulty": {
                "enabled": true,
                "updateInterval": 1800,
                "stepInterval": 10800,
                "maximumPeriod": 604800
            },
            "price": {    "monitoring": {
        "daemon": {
            "checkInterval": 60,
            "rpcMethod": "getblockcount"
        },
        "wallet": {
            "checkInterval": 60,
            "rpcMethod": "getbalance"
        }
    },
    "charts": {
        "pool": {
            "hashrate": {
                "enabled": true,
                "updateInterval": 60,
                "stepInterval": 1800,
                "maximumPeriod": 86400
            },
            "workers": {
                "enabled": true,
                "updateInterval": 60,
                "stepInterval": 1800,
                "maximumPeriod": 86400
            },
            "difficulty": {
                "enabled": true,
                "updateInterval": 1800,
                "stepInterval": 10800,
                "maximumPeriod": 604800
            },
            "price": {
                "enabled": true,
                "updateInterval": 1800,
                "stepInterval": 10800,
                "maximumPeriod": 604800
            },
            "profit": {
                "enabled": true,
                "updateInterval": 1800,
                "stepInterval": 10800,
                "maximumPeriod": 604800
            }
        },
        "user": {
            "hashrate": {
                "enabled": true,
                "updateInterval": 180,
                "stepInterval": 1800,
                "maximumPeriod": 86400
            },
            "payments": {
                "enabled": true
            }
        }
    }
}

                "enabled": true,
                "updateInterval": 1800,
                "stepInterval": 10800,
                "maximumPeriod": 604800
            },
            "profit": {
                "enabled": true,
                "updateInterval": 1800,
                "stepInterval": 10800,
                "maximumPeriod": 604800
            }
        },
        "user": {
            "hashrate": {
                "enabled": true,
                "updateInterval": 180,
                "stepInterval": 1800,
                "maximumPeriod": 86400
            },
            "payments": {
                "enabled": true
            }
        }
    }
}

this is the error:
`2018-02-24 18:19:21 [master] Pool spawned on 8 thread(s)locktemplate {"code":-9,"message":"Core is busy"}
2018-02-24 18:19:21 [unlocker] StartedError polling getblocktemplate {"code":-9,"message":"Core is busy"}
2018-02-24 18:19:21 [payments] Startedo config.json
2018-02-24 18:19:21 [unlocker] No blocks candidates in redis
2018-02-24 18:19:21 [charts] Started
2018-02-24 18:19:21 [chartsDataCollector] Started
2018-02-24 18:19:21 [payments] No workers' balances reached the minimum payment threshold
2018-02-24 18:19:21 [charts] Started

Error: bind EADDRINUSE
    at errnoException (net.js:905:11)
    at net.js:1085:30
    at Object.3:1 (cluster.js:594:5)
    at handleResponse (cluster.js:171:41)
    at respond (cluster.js:192:5)
    at handleMessage (cluster.js:202:5)
    at process.emit (events.js:117:20)
    at handleMessage (child_process.js:322:10)
    at child_process.js:396:7
    at process.handleConversion.net.Native.got (child_process.js:91:7)

Error: bind EADDRINUSE
    at errnoException (net.js:905:11)
    at net.js:1085:30
    at Object.3:1 (cluster.js:594:5)
    at handleResponse (cluster.js:171:41)
    at respond (cluster.js:192:5)
    at handleMessage (cluster.js:202:5)
    at process.emit (events.js:117:20)
    at handleMessage (child_process.js:322:10)
    at child_process.js:396:7
    at process.handleConversion.net.Native.got (child_process.js:91:7)

2018-02-24 18:19:21 [api] Stat collection finished: 19 ms redis, 18 ms daemon
2018-02-24 18:19:21 [api] Broadcasting to 0 visitors and 0 address lookups
2018-02-24 18:19:21 [master] API died, spawning replacement...
2018-02-24 18:19:21 [pool] (Thread 2) Error polling getblocktemplate {"code":-9,"message":"Core is busy"}
2018-02-24 18:19:21 [pool] (Thread 2) Could not start pool
2018-02-24 18:19:21 [pool] (Thread 3) Error polling getblocktemplate {"code":-9,"message":"Core is busy"}
2018-02-24 18:19:21 [pool] (Thread 3) Could not start pool
2018-02-24 18:19:21 [pool] (Thread 4) Error polling getblocktemplate {"code":-9,"message":"Core is busy"}
2018-02-24 18:19:21 [pool] (Thread 4) Could not start pool
2018-02-24 18:19:21 [pool] (Thread 6) Error polling getblocktemplate {"code":-9,"message":"Core is busy"}
2018-02-24 18:19:21 [pool] (Thread 6) Could not start pool
2018-02-24 18:19:21 [pool] (Thread 8) Error polling getblocktemplate {"code":-9,"message":"Core is busy"}
2018-02-24 18:19:21 [pool] (Thread 8) Could not start pool
2018-02-24 18:19:21 [pool] (Thread 7) Error polling getblocktemplate {"code":-9,"message":"Core is busy"}
2018-02-24 18:19:21 [pool] (Thread 7) Could not start pool
2018-02-24 18:19:21 [pool] (Thread 1) Error polling getblocktemplate {"code":-9,"message":"Core is busy"}
2018-02-24 18:19:21 [pool] (Thread 1) Could not start pool
2018-02-24 18:19:21 [pool] (Thread 5) Error polling getblocktemplate {"code":-9,"message":"Core is busy"}
2018-02-24 18:19:21 [pool] (Thread 5) Could not start pool
2018-02-24 18:19:22 [pool] (Thread 2) Error polling getblocktemplate {"code":-9,"message":"Core is busy"}
2018-02-24 18:19:22 [pool] (Thread 3) Error polling getblocktemplate {"code":-9,"message":"Core is busy"}
2018-02-24 18:19:22 [pool] (Thread 4) Error polling getblocktemplate {"code":-9,"message":"Core is busy"}
2018-02-24 18:19:22 [pool] (Thread 6) Error polling getblocktemplate {"code":-9,"message":"Core is busy"}
2018-02-24 18:19:22 [pool] (Thread 8) Error polling getblocktemplate {"code":-9,"message":"Core is busy"}
2018-02-24 18:19:22 [pool] (Thread 7) Error polling getblocktemplate {"code":-9,"message":"Core is busy"}
2018-02-24 18:19:22 [pool] (Thread 1) Error polling getblocktemplate {"code":-9,"message":"Core is busy"}
2018-02-24 18:19:22 [pool] (Thread 5) Error polling getblocktemplate {"code":-9,"message":"Core is busy"}
2018-02-24 18:19:23 [charts] Started`

**Comment by maurosbicego** [comment]
Is your Daemon fully synced?
