### ISSUE TITLE
 [master] Block unlocker died, spawning replacement...

### ISSUE THREAD

**Issue by L2ne** [fancoder/cryptonote-universal-pool#107]
TypeError: Object true has no method 'map'
    at async.waterfall.orphanCommands (/home/ubuntu/pool/lib/blockUnlocker.js:82:40)
    at nextTask (/home/ubuntu/pool/node_modules/async/dist/async.js:5310:14)
    at next (/home/ubuntu/pool/node_modules/async/dist/async.js:5317:9)
    at /home/ubuntu/pool/node_modules/async/dist/async.js:958:16
    at /home/ubuntu/pool/lib/blockUnlocker.js:75:17
    at /home/ubuntu/pool/node_modules/async/dist/async.js:3358:25
    at /home/ubuntu/pool/node_modules/async/dist/async.js:473:16
    at iteratorCallback (/home/ubuntu/pool/node_modules/async/dist/async.js:1048:13)
    at /home/ubuntu/pool/node_modules/async/dist/async.js:958:16
    at /home/ubuntu/pool/node_modules/async/dist/async.js:3355:13

What is causing this ?

**Comment by L2ne** [comment]
had the wrong async version
