### ISSUE TITLE
Pool fails to build CentOS 6 (Kernel 2.6.32-642.1.1.el6.x86_64)

### ISSUE THREAD

**Issue by JPaulMora** [fancoder/cryptonote-universal-pool#31]
```
npm update
async@1.5.2 node_modules/async
cli-color@1.1.0 node_modules/cli-color
├── ansi-regex@2.0.0
├── d@0.1.1
├── timers-ext@0.1.0 (next-tick@0.2.2)
├── es6-iterator@2.0.0 (es6-symbol@3.1.0)
├── memoizee@0.3.10 (next-tick@0.2.2, lru-queue@0.1.0, event-emitter@0.3.4, es6-weak-map@0.1.4)
└── es5-ext@0.10.12 (es6-symbol@3.1.0)

> cryptonote-util@0.0.1 install /sata/cryptonote-universal-pool/node_modules/cryptonote-util
> node-gyp rebuild

make: Entering directory `/sata/cryptonote-universal-pool/node_modules/cryptonote-util/build'
make: *** No rule to make target `/.node-gyp/0.10.46/include/node/common.gypi', needed by `Makefile'.  Stop.
make: Leaving directory `/sata/cryptonote-universal-pool/node_modules/cryptonote-util/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 2.6.32-642.1.1.el6.x86_64
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /sata/cryptonote-universal-pool/node_modules/cryptonote-util
gyp ERR! node -v v0.10.46
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 

> multi-hashing@0.0.9 install /sata/cryptonote-universal-pool/node_modules/multi-hashing
> node-gyp rebuild

make: Entering directory `/sata/cryptonote-universal-pool/node_modules/multi-hashing/build'
make: *** No rule to make target `/.node-gyp/0.10.46/include/node/common.gypi', needed by `Makefile'.  Stop.
make: Leaving directory `/sata/cryptonote-universal-pool/node_modules/multi-hashing/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 2.6.32-642.1.1.el6.x86_64
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /sata/cryptonote-universal-pool/node_modules/multi-hashing
gyp ERR! node -v v0.10.46
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
redis@2.6.2 node_modules/redis
├── double-ended-queue@2.1.0-0
├── redis-parser@2.0.3
└── redis-commands@1.2.0
npm WARN engine deep-extend@0.4.1: wanted: {"node":">=0.12.0","iojs":">=1.0.0"} (current: {"node":"0.10.46","npm":"2.15.1"})
npm WARN engine deep-extend@0.4.1: wanted: {"node":">=0.12.0","iojs":">=1.0.0"} (current: {"node":"0.10.46","npm":"2.15.1"})
dateformat@1.0.12 node_modules/dateformat
├── get-stdin@4.0.1
└── meow@3.7.0 (map-obj@1.0.1, decamelize@1.2.0, trim-newlines@1.0.0, object-assign@4.1.0, camelcase-keys@2.1.0, minimist@1.2.0, loud-rejection@1.6.0, redent@1.0.0, read-pkg-up@1.0.1, normalize-package-data@2.3.5)
/
> bignum@0.12.5 install /sata/cryptonote-universal-pool/node_modules/base58-native/node_modules/bignum
> node-pre-gyp install --fallback-to-build

[bignum] Success: "/sata/cryptonote-universal-pool/node_modules/base58-native/node_modules/bignum/binding/bignum.node" is installed via remote

> bignum@0.12.5 install /sata/cryptonote-universal-pool/node_modules/bignum
> node-pre-gyp install --fallback-to-build

base58-native@0.1.4 node_modules/base58-native
└── bignum@0.12.5 (nan@2.4.0, node-pre-gyp@0.6.29)
[bignum] Success: "/sata/cryptonote-universal-pool/node_modules/bignum/binding/bignum.node" is installed via remote
bignum@0.12.5 node_modules/bignum
├── nan@2.4.0
└── node-pre-gyp@0.6.29 (semver@5.2.0, nopt@3.0.6, mkdirp@0.5.1, rc@1.1.6, tar@2.2.1, rimraf@2.5.3, tar-pack@3.1.4, npmlog@3.1.2, request@2.73.0)
npm ERR! Linux 2.6.32-642.1.1.el6.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "update"
npm ERR! node v0.10.46
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE

npm ERR! cryptonote-util@0.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cryptonote-util@0.0.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the cryptonote-util package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs cryptonote-util
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls cryptonote-util
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /sata/cryptonote-universal-pool/npm-debug.log
```

**Comment by donvito-pl** [comment]
It fails to build on almost every possible distribution or node configuration. 
Would be nice if developers or pool runners could specify exact packages versions against which the pool actually builds and works with.

**Comment by netmonk** [comment]
The pool code is two years
Old....

**Comment by pmitchev** [comment]
This pool works only on Ubuntu 14 . At least I am able to got it working on this OS

**Comment by JPaulMora** [comment]
@pmitchev could you `npm list` your working copy for us?

**Comment by pmitchev** [comment]
https://github.com/forknote/forknote-pool/blob/master/package.json

This is the exact package file I use. It's a little different. Sorry for the delayed reply

**Comment by JPaulMora** [comment]
Awesome, thanks.
