### ISSUE TITLE
Failed to parse block

### ISSUE THREAD

**Issue by tanshaoliang** [fancoder/cryptonote-universal-pool#34]
The console print 'startum_recv_line failed...' when i start cryptonote miner on my pc.
this is error msg print pool console:
Error: Failed to parse block
    at Object.BlockTemplate.nextBlob (/data/src/cryptonote-universal-pool/lib/pool.js:120:23)
    at Object.Miner.getJob (/data/src/cryptonote-universal-pool/lib/pool.js:297:41)
    at handleMinerMethod (/data/src/cryptonote-universal-pool/lib/pool.js:492:28)
    at handleMessage (/data/src/cryptonote-universal-pool/lib/pool.js:606:13)
    at Socket.socket.on.on.on.pushMessage (/data/src/cryptonote-universal-pool/lib/pool.js:660:25)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:746:14)
    at Socket.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)
    at emitReadable (_stream_readable.js:404:5)
--------------------------------------------------------
what's wrong? Thanks.

**Comment by dam2k** [comment]
You are probably using monero (getmonero.org). I also had this error when they hardforked the blockchain from v2 to v3 blocks a couple of months ago.

**Comment by tanshaoliang** [comment]
@dam2k 
Yes,indeed. i using monero(https://github.com/monero-project/monero) as coin daemon. 
so,how did you solve this problem.

**Comment by dam2k** [comment]
@tanshaoliang I'm using the fork from zone117 (https://github.com/zone117x/node-cryptonote-pool).
If anyone find a better way, please let us know.

**Comment by sennevb** [comment]
same problem..

**Comment by vvzar** [comment]
same problem

**Comment by gjnardoni** [comment]
same problem
