### ISSUE TITLE
Error: Failed to parse block

### ISSUE THREAD

**Issue by phucvinh52** [fancoder/cryptonote-universal-pool#36]
Hello all,
I have a poblem with my pool.
When i run "node init.js" and run minerd, it occur that error.
```

2017-01-22 06:18:18 [api] Broadcasting to 2 visitors and 0 address lookups
Error: Failed to parse block
    at Object.BlockTemplate.nextBlob (/pool/lib/pool.js:120:23)
    at Object.Miner.getJob (/pool/lib/pool.js:297:41)
    at handleMinerMethod (/pool/lib/pool.js:492:28)
    at handleMessage (/pool/lib/pool.js:606:13)
    at Socket.socket.on.on.on.pushMessage (/pool/lib/pool.js:660:25)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:746:14)
    at Socket.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)
    at emitReadable (_stream_readable.js:404:5)

2017-01-22 06:18:20 [master] Pool fork 1 died, spawning replacement worker...
```

Do you have any way to resolve this poblem? Thank all

**Comment by ub14** [comment]
Who solved this problem?

----------------------------------------------------------------
Tuned coin bytecoin. When the miner is turned on, the error "Error: Failed to parse block" appears.

Once it was possible to begin to extract a coin for a minute, after the restart of the miner again such an error went.

Bytecoind and sipmlewallet updated. All the default settings, added only sipmlewallet (--rpc-bind-port 8082 --daemon-port 8081)

Tell me, what's the problem? I beat the fifth day, I can not find an error.


> 2017-03-17 01:29:44 [payments] No workers' balances reached the minimum payment threshold
> 2017-03-17 01:29:53 [api] Stat collection finished: 27 ms redis, 9004 ms daemon
> 2017-03-17 01:29:53 [api] Broadcasting to 0 visitors and 0 address lookups
> 2017-03-17 01:29:55 [pool] (Thread 1) New block to mine at height 1222720 w/ difficulty of 46961927
> 2017-03-17 01:29:55 [pool] (Thread 1) Started server listening on port 5555
> 2017-03-17 01:30:12 [pool] (Thread 2) New block to mine at height 1222720 w/ difficulty of 46961927
> 2017-03-17 01:30:12 [pool] (Thread 2) Started server listening on port 5555
> 2017-03-17 01:30:14 [unlocker] No blocks candidates in redis
> 
> Error: Failed to parse block
>     at Object.BlockTemplate.nextBlob (/home/ub14/poolx/lib/pool.js:128:23)
>     at Object.Miner.getJob (/home/ub14/poolx/lib/pool.js:301:41)`
>     at handleMinerMethod (/home/ub14/poolx/lib/pool.js:510:28)
>     at handleMessage (/home/ub14/poolx/lib/pool.js:644:13)
>     at Socket.socket.on.on.on.pushMessage (/home/ub14/poolx/lib/pool.js:698:25)
>     at Socket.EventEmitter.emit (events.js:95:17)
>     at Socket.<anonymous> (_stream_readable.js:746:14)
>     at Socket.EventEmitter.emit (events.js:92:17)
>     at emitReadable_ (_stream_readable.js:408:10)
>     at emitReadable (_stream_readable.js:404:5)
> 
> 2017-03-17 01:30:37 [master] Pool fork 2 died, spawning replacement worker...
> 2017-03-17 01:30:42 [pool] (Thread 1) New block to mine at height 1222721 w/ difficulty of 47045153
> 2017-03-17 01:30:42 [api] Stat collection finished: 6 ms redis, 43443 ms daemon
> 2017-03-17 01:30:42 [api] Broadcasting to 0 visitors and 0 address lookups
> 2017-03-17 01:30:44 [unlocker] No blocks candidates in redis

**Comment by Nashatyrev** [comment]
+1 on Monero

**Comment by nibbons** [comment]
Any fix for this for non-monero coins like DigitalNote that you're aware of?  I'm getting the same error but only when a miner tries to connect and can't figure it out: https://i.imgur.com/5vh9yQK.jpg

**Comment by armpdq** [comment]
same issue with monero. any solution?

**Comment by MelonSmasher** [comment]
Same issue

**Comment by OfficiallyUndead** [comment]
same issue. any solution?
I have found that the error is coming from the cryptonote-util package

**Comment by KelvinJones** [comment]
Same issue for me too.  Any solution? Hoping...

**Comment by OfficiallyUndead** [comment]
Still looking for solution if somebody has one?

**Comment by KelvinJones** [comment]
Mine is fine now. I can't remember exactly but I believe it has to do with syncing the block chain.  Once you bytecoin Daemon is fully up to date, not just connected to the network, the pool will run fine.  That seemed to work for for me. Hope that helps.


________________________________

**Comment by OfficiallyUndead** [comment]
That was the problem but also node version was wrong.

I have one other question, I have pool working now but it's not adding pending balance to miners. So they never get processed for payments. Any ideas what could be the issue?

**Comment by KelvinJones** [comment]
Not sure about that, I'm seeing the same behaviour on mine. However, I think it has to do with the "maturity".  My guess is after it collects 10 blocks it will start paying out...but that's purely a guess.
________________________________

**Comment by danielbjornadal** [comment]
+1

**Comment by armpdq** [comment]
lol guys. you have to set
        "async": "1.5.2",
and
        "cryptonote-util": "git://github.com/Snipa22/node-cryptonote-util#xmr-Nan-2.0"
in your package.json and rebuild app

**Comment by msilvoli** [comment]
Thanks @armpdq  !
Now it's working.

**Comment by karoljoc** [comment]
Oh these pools are terrible :-( Have been trying to get my pool to accept connections from a windows wallet but just crashes every time. 

2018-01-21 21:36:19 [api] Broadcasting to 0 visitors and 0 address lookups

Error: Failed to parse block
    at Object.BlockTemplate.nextBlob (/home/karol/DigitalNoteServ/lib/pool.js:122:23)
    at Object.Miner.getJob (/home/karol/DigitalNoteServ/lib/pool.js:299:41)
    at handleMinerMethod (/home/karol/DigitalNoteServ/lib/pool.js:494:28)
    at handleMessage (/home/karol/DigitalNoteServ/lib/pool.js:624:13)
    at Socket.socket.on.on.on.pushMessage (/home/karol/DigitalNoteServ/lib/pool.js:678:25)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:765:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at emitReadable (_stream_readable.js:423:5)

2018-01-21 21:36:19 [master] Pool fork 3 died, spawning replacement worker...

Have really tried everything possible. I see there is a lot of warnings when doing npm update.  This is for XDN. Tried changing cryptonote-util and still nothng.  Is it maybe that I am using ubuntu 14.04?

**Comment by CerveloFellow** [comment]
Any luck fixing this?  I'm trying with ITNS, and no matter what I do I can't seem to fix this error.  I get the same error as Karoljoc does

Error: Failed to parse block
    at Object.BlockTemplate.nextBlob (/home/paul/pool/lib/pool.js:120:23)
    at Object.Miner.getJob (/home/paul/pool/lib/pool.js:297:41)
    at handleMinerMethod (/home/paul/pool/lib/pool.js:492:28)
    at handleMessage (/home/paul/pool/lib/pool.js:606:13)
    at Socket.socket.on.on.on.pushMessage (/home/paul/pool/lib/pool.js:660:25)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:746:14)
    at Socket.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)
    at emitReadable (_stream_readable.js:404:5)


2018-02-18 20:55:45 [pool] (Thread 4) Invalid method: mining.subscribe ([]) from

I've tried several miners and they all cause the same error.  Thanks.
