### ISSUE TITLE
Cannot read property 'pool' of undefined

### ISSUE THREAD

**Issue by dinho-afsn** [fancoder/cryptonote-universal-pool#51]
TypeError: Cannot read property 'pool' of undefined
    at /var/www/pool/lib/charts.js:154:30
    at IncomingMessage.<anonymous> (/var/www/pool/lib/apiInterfaces.js:31:17)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)

any help?

**Comment by coinsinternet** [comment]
I have the same issue.
If you resolved, i'll appreciate some advice. 
Thanks

**Comment by zhmrab** [comment]
Any update on that?

**Comment by zhiapp-com** [comment]
i have the same issue.
