### ISSUE TITLE
Cryptonote-util missing from npm

### ISSUE THREAD

**Issue by valiant1x** [fancoder/cryptonote-universal-pool#54]
It seems cryptonote-util is broken and not building properly. Referenced log file: https://pastebin.com/M5raQfQe
```
[intense@server1 pool]$ npm update

> cryptonote-util@0.0.1 install /home/intense/pool/node_modules/cryptonote-util
> node-gyp rebuild

make: Entering directory `/home/intense/pool/node_modules/cryptonote-util/build'
  CXX(target) Release/obj.target/cryptonote/src/main.o
In file included from ../src/contrib/epee/include/serialization/keyvalue_serialization.h:31,
                 from ../src/cryptonote_core/cryptonote_basic.h:20,
                 from ../src/main.cc:8:
../src/contrib/epee/include/misc_log_ex.h:32:18: warning: atomic: No such file or directory
In file included from /home/intense/.node-gyp/6.11.2/include/node/node.h:42,
                 from ../src/main.cc:2:
/home/intense/.node-gyp/6.11.2/include/node/v8.h:345: error: expected unqualified-id before ‘using’
/home/intense/.node-gyp/6.11.2/include/node/v8.h: In constructor ‘v8::MaybeLocal<T>::MaybeLocal()’:
/home/intense/.node-gyp/6.11.2/include/node/v8.h:362: error: ‘nullptr’ was not declared in this scope
/home/intense/.node-gyp/6.11.2/include/node/v8.h: In member function ‘bool v8::MaybeLocal<T>::IsEmpty() const’:
/home/intense/.node-gyp/6.11.2/include/node/v8.h:369: error: ‘nullptr’ was not declared in this scope
/home/intense/.node-gyp/6.11.2/include/node/v8.h: In member function ‘bool v8::MaybeLocal<T>::ToLocal(v8::Local<S>*) const’:
/home/intense/.node-gyp/6.11.2/include/node/v8.h:373: error: ‘nullptr’ was not declared in this scope
/home/intense/.node-gyp/6.11.2/include/node/v8.h: In member function ‘bool v8::WeakCallbackInfo<T>::IsFirstPass() const’:
/home/intense/.node-gyp/6.11.2/include/node/v8.h:441: error: ‘nullptr’ was not declared in this scope
/home/intense/.node-gyp/6.11.2/include/node/v8.h: At global scope:
/home/intense/.node-gyp/6.11.2/include/node/v8.h:481: error: expected unqualified-id before ‘using’
/home/intense/.node-gyp/6.11.2/include/node/v8.h: In constructor ‘v8::Global<T>::Global()’:
/home/intense/.node-gyp/6.11.2/include/node/v8.h:820: error: ‘nullptr’ was not declared in this scope
/home/intense/.node-gyp/6.11.2/include/node/v8.h: In constructor ‘v8::Global<T>::Global(v8::Global<T>&&)’:
/home/intense/.node-gyp/6.11.2/include/node/v8.h:845: error: ‘nullptr’ was not declared in this scope
/home/intense/.node-gyp/6.11.2/include/node/v8.h: In member function ‘v8::Global<T>& v8::Global<T>::operator=(v8::Global<S>&&)’:
/home/intense/.node-gyp/6.11.2/include/node/v8.h:857: error: ‘nullptr’ was not declared in this scope
/home/intense/.node-gyp/6.11.2/include/node/v8.h: At global scope:
/home/intense/.node-gyp/6.11.2/include/node/v8.h:882: error: expected unqualified-id before ‘using’
/home/intense/.node-gyp/6.11.2/include/node/v8.h:1119: error: ‘nullptr’ was not declared in this scope
/home/intense/.node-gyp/6.11.2/include/node/v8.h:1125: error: ‘nullptr’ was not declared in this scope
/home/intense/.node-gyp/6.11.2/include/node/v8.h: In member function ‘v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>) const’:
/home/intense/.node-gyp/6.11.2/include/node/v8.h:3279: error: ‘nullptr’ was not declared in this scope
/home/intense/.node-gyp/6.11.2/include/node/v8.h: At global scope:
/home/intense/.node-gyp/6.11.2/include/node/v8.h:4499: error: ‘nullptr’ was not declared in this scope
/home/intense/.node-gyp/6.11.2/include/node/v8.h:4515: error: ‘nullptr’ was not declared in this scope
/home/intense/.node-gyp/6.11.2/include/node/v8.h: In member function ‘v8::Local<T> v8::MaybeLocal<T>::ToLocalChecked()’:
/home/intense/.node-gyp/6.11.2/include/node/v8.h:7539: error: ‘nullptr’ was not declared in this scope
In file included from ../src/cryptonote_core/cryptonote_basic.h:16,
                 from ../src/main.cc:8:
../src/serialization/binary_archive.h: At global scope:
../src/serialization/binary_archive.h:18: warning: expected [error|warning|ignored] after ‘#pragma GCC diagnostic’
../src/serialization/binary_archive.h:169: warning: expected [error|warning|ignored] after ‘#pragma GCC diagnostic’
In file included from ../src/contrib/epee/include/misc_log_ex.h:54,
                 from ../src/contrib/epee/include/serialization/keyvalue_serialization.h:31,
                 from ../src/cryptonote_core/cryptonote_basic.h:20,
                 from ../src/main.cc:8:
../src/contrib/epee/include/string_tools.h:184: warning: expected [error|warning|ignored] after ‘#pragma GCC diagnostic’
../src/contrib/epee/include/string_tools.h:185: warning: unknown option after ‘#pragma GCC diagnostic’ kind
../src/contrib/epee/include/string_tools.h: In function ‘bool epee::string_tools::get_xtype_from_string(XType&, const std::string&)’:
../src/contrib/epee/include/string_tools.h:191: error: expected initializer before ‘:’ token
../src/contrib/epee/include/string_tools.h:196: error: expected primary-expression before ‘}’ token
../src/contrib/epee/include/string_tools.h:196: error: expected ‘;’ before ‘}’ token
../src/contrib/epee/include/string_tools.h:196: error: expected primary-expression before ‘}’ token
../src/contrib/epee/include/string_tools.h:196: error: expected ‘)’ before ‘}’ token
../src/contrib/epee/include/string_tools.h:196: error: expected primary-expression before ‘}’ token
../src/contrib/epee/include/string_tools.h:196: error: expected ‘;’ before ‘}’ token
../src/contrib/epee/include/string_tools.h: At global scope:
../src/contrib/epee/include/string_tools.h:215: warning: expected [error|warning|ignored] after ‘#pragma GCC diagnostic’
In file included from ../src/contrib/epee/include/misc_log_ex.h:55,
                 from ../src/contrib/epee/include/serialization/keyvalue_serialization.h:31,
                 from ../src/cryptonote_core/cryptonote_basic.h:20,
                 from ../src/main.cc:8:
../src/contrib/epee/include/time_helper.h: In function ‘std::string epee::misc_utils::get_time_str(const time_t&)’:
../src/contrib/epee/include/time_helper.h:62: error: #pragma GCC diagnostic not allowed inside functions
../src/contrib/epee/include/time_helper.h:65: error: #pragma GCC diagnostic not allowed inside functions
../src/contrib/epee/include/time_helper.h: In function ‘std::string epee::misc_utils::get_time_str_v2(const time_t&)’:
../src/contrib/epee/include/time_helper.h:84: error: #pragma GCC diagnostic not allowed inside functions
../src/contrib/epee/include/time_helper.h:87: error: #pragma GCC diagnostic not allowed inside functions
../src/contrib/epee/include/time_helper.h: In function ‘std::string epee::misc_utils::get_internet_time_str(const time_t&)’:
../src/contrib/epee/include/time_helper.h:112: error: #pragma GCC diagnostic not allowed inside functions
../src/contrib/epee/include/time_helper.h:115: error: #pragma GCC diagnostic not allowed inside functions
../src/contrib/epee/include/time_helper.h: In function ‘std::string epee::misc_utils::get_time_interval_string(const time_t&)’:
../src/contrib/epee/include/time_helper.h:124: error: #pragma GCC diagnostic not allowed inside functions
../src/contrib/epee/include/time_helper.h:133: error: #pragma GCC diagnostic not allowed inside functions
In file included from ../src/contrib/epee/include/serialization/keyvalue_serialization.h:31,
                 from ../src/cryptonote_core/cryptonote_basic.h:20,
                 from ../src/main.cc:8:
../src/contrib/epee/include/misc_log_ex.h: In function ‘bool epee::log_space::is_stdout_a_tty()’:
../src/contrib/epee/include/misc_log_ex.h:205: error: expected initializer before ‘<’ token
../src/contrib/epee/include/misc_log_ex.h:206: error: expected initializer before ‘<’ token
../src/contrib/epee/include/misc_log_ex.h:208: error: ‘initialized’ was not declared in this scope
../src/contrib/epee/include/misc_log_ex.h:208: error: ‘memory_order_acquire’ is not a member of ‘std’
../src/contrib/epee/include/misc_log_ex.h:213: error: ‘is_a_tty’ was not declared in this scope
../src/contrib/epee/include/misc_log_ex.h:213: error: ‘memory_order_relaxed’ is not a member of ‘std’
../src/contrib/epee/include/misc_log_ex.h:215: error: ‘memory_order_release’ is not a member of ‘std’
../src/contrib/epee/include/misc_log_ex.h:218: error: ‘is_a_tty’ was not declared in this scope
../src/contrib/epee/include/misc_log_ex.h:218: error: ‘memory_order_relaxed’ is not a member of ‘std’
In file included from ../src/contrib/epee/include/serialization/keyvalue_serialization.h:31,
                 from ../src/cryptonote_core/cryptonote_basic.h:20,
                 from ../src/main.cc:8:
../src/contrib/epee/include/misc_log_ex.h: At global scope:
../src/contrib/epee/include/misc_log_ex.h:980: warning: expected [error|warning|ignored] after ‘#pragma GCC diagnostic’
../src/contrib/epee/include/misc_log_ex.h:981: warning: unknown option after ‘#pragma GCC diagnostic’ kind
../src/contrib/epee/include/misc_log_ex.h:989: warning: expected [error|warning|ignored] after ‘#pragma GCC diagnostic’
In file included from ../src/contrib/epee/include/serialization/keyvalue_serialization.h:33,
                 from ../src/cryptonote_core/cryptonote_basic.h:20,
                 from ../src/main.cc:8:
../src/contrib/epee/include/serialization/keyvalue_serialization_overloads.h: In function ‘bool epee::serialization::serialize_stl_container_t_obj(const stl_container&, t_storage&, typename t_storage::hsection, const char*)’:
../src/contrib/epee/include/serialization/keyvalue_serialization_overloads.h:167: error: ‘nullptr’ was not declared in this scope
../src/contrib/epee/include/serialization/keyvalue_serialization_overloads.h: In function ‘bool epee::serialization::unserialize_stl_container_t_obj(stl_container&, t_storage&, typename t_storage::hsection, const char*)’:
../src/contrib/epee/include/serialization/keyvalue_serialization_overloads.h:186: error: ‘nullptr’ was not declared in this scope
In file included from ../src/main.cc:8:
../src/cryptonote_core/cryptonote_basic.h: In static member function ‘static size_t cryptonote::transaction::get_signature_size(const cryptonote::txin_v&)’:
../src/cryptonote_core/cryptonote_basic.h:312: error: no matching function for call to ‘apply_visitor(cryptonote::transaction::get_signature_size(const cryptonote::txin_v&)::txin_signature_size_visitor, const boost::variant<cryptonote::txin_gen, cryptonote::txin_to_script, cryptonote::txin_to_scripthash, cryptonote::txin_to_key, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>&)’
../src/cryptonote_core/cryptonote_basic.h: In static member function ‘static size_t cryptonote::bb_transaction::get_signature_size(const cryptonote::txin_v&)’:
../src/cryptonote_core/cryptonote_basic.h:349: error: no matching function for call to ‘apply_visitor(cryptonote::bb_transaction::get_signature_size(const cryptonote::txin_v&)::txin_signature_size_visitor, const boost::variant<cryptonote::txin_gen, cryptonote::txin_to_script, cryptonote::txin_to_scripthash, cryptonote::txin_to_key, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>&)’
In file included from ../src/main.cc:8:
../src/cryptonote_core/cryptonote_basic.h: At global scope:
../src/cryptonote_core/cryptonote_basic.h:544: error: ‘nullptr’ was not declared in this scope
../src/cryptonote_core/cryptonote_basic.h:544: error: ‘nullptr’ was not declared in this scope
../src/cryptonote_core/cryptonote_basic.h:544: error: ‘nullptr’ was not declared in this scope
In file included from ../src/cryptonote_core/cryptonote_format_utils.h:6,
                 from ../src/main.cc:9:
../src/cryptonote_protocol/cryptonote_protocol_defs.h:25: error: ‘nullptr’ was not declared in this scope
../src/cryptonote_protocol/cryptonote_protocol_defs.h:25: error: ‘nullptr’ was not declared in this scope
../src/cryptonote_protocol/cryptonote_protocol_defs.h:25: error: ‘nullptr’ was not declared in this scope
../src/cryptonote_protocol/cryptonote_protocol_defs.h:45: error: ‘nullptr’ was not declared in this scope
../src/cryptonote_protocol/cryptonote_protocol_defs.h:45: error: ‘nullptr’ was not declared in this scope
../src/cryptonote_protocol/cryptonote_protocol_defs.h:45: error: ‘nullptr’ was not declared in this scope
../src/cryptonote_protocol/cryptonote_protocol_defs.h:64: error: ‘nullptr’ was not declared in this scope
../src/cryptonote_protocol/cryptonote_protocol_defs.h:64: error: ‘nullptr’ was not declared in this scope
../src/cryptonote_protocol/cryptonote_protocol_defs.h:64: error: ‘nullptr’ was not declared in this scope
../src/cryptonote_protocol/cryptonote_protocol_defs.h:81: error: ‘nullptr’ was not declared in this scope
../src/cryptonote_protocol/cryptonote_protocol_defs.h:81: error: ‘nullptr’ was not declared in this scope
../src/cryptonote_protocol/cryptonote_protocol_defs.h:81: error: ‘nullptr’ was not declared in this scope
../src/cryptonote_protocol/cryptonote_protocol_defs.h:99: error: ‘nullptr’ was not declared in this scope
../src/cryptonote_protocol/cryptonote_protocol_defs.h:99: error: ‘nullptr’ was not declared in this scope
../src/cryptonote_protocol/cryptonote_protocol_defs.h:99: error: ‘nullptr’ was not declared in this scope
../src/cryptonote_protocol/cryptonote_protocol_defs.h:114: error: ‘nullptr’ was not declared in this scope
../src/cryptonote_protocol/cryptonote_protocol_defs.h:114: error: ‘nullptr’ was not declared in this scope
../src/cryptonote_protocol/cryptonote_protocol_defs.h:114: error: ‘nullptr’ was not declared in this scope
In file included from ../src/cryptonote_core/cryptonote_format_utils.h:6,
                 from ../src/main.cc:9:
../src/cryptonote_protocol/cryptonote_protocol_defs.h:128: error: ‘nullptr’ was not declared in this scope
../src/cryptonote_protocol/cryptonote_protocol_defs.h:128: error: ‘nullptr’ was not declared in this scope
../src/cryptonote_protocol/cryptonote_protocol_defs.h:128: error: ‘nullptr’ was not declared in this scope
../src/cryptonote_protocol/cryptonote_protocol_defs.h:144: error: ‘nullptr’ was not declared in this scope
../src/cryptonote_protocol/cryptonote_protocol_defs.h:144: error: ‘nullptr’ was not declared in this scope
../src/cryptonote_protocol/cryptonote_protocol_defs.h:144: error: ‘nullptr’ was not declared in this scope
In file included from ../src/cryptonote_core/cryptonote_format_utils.h:9,
                 from ../src/main.cc:9:
../src/cryptonote_core/account.h:20: error: ‘nullptr’ was not declared in this scope
../src/cryptonote_core/account.h:20: error: ‘nullptr’ was not declared in this scope
../src/cryptonote_core/account.h:20: error: ‘nullptr’ was not declared in this scope
../src/cryptonote_core/account.h:51: error: ‘nullptr’ was not declared in this scope
../src/cryptonote_core/account.h:51: error: ‘nullptr’ was not declared in this scope
../src/cryptonote_core/account.h:51: error: ‘nullptr’ was not declared in this scope
In file included from ../src/main.cc:9:
../src/cryptonote_core/cryptonote_format_utils.h: In function ‘bool cryptonote::find_tx_extra_field_by_type(const std::vector<boost::variant<cryptonote::tx_extra_padding, cryptonote::tx_extra_pub_key, cryptonote::tx_extra_nonce, cryptonote::tx_extra_merge_mining_tag, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>, std::allocator<boost::variant<cryptonote::tx_extra_padding, cryptonote::tx_extra_pub_key, cryptonote::tx_extra_nonce, cryptonote::tx_extra_merge_mining_tag, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> > >&, T&)’:
../src/cryptonote_core/cryptonote_format_utils.h:50: error: expected primary-expression before ‘[’ token
../src/cryptonote_core/cryptonote_format_utils.h:50: error: expected primary-expression before ‘]’ token
../src/cryptonote_core/cryptonote_format_utils.h:50: error: expected primary-expression before ‘const’
../src/cryptonote_core/cryptonote_format_utils.h:50: error: unable to deduce ‘auto’ from ‘std::find_if(tx_extra_fields->std::vector<_Tp, _Alloc>::begin [with _Tp = boost::variant<cryptonote::tx_extra_padding, cryptonote::tx_extra_pub_key, cryptonote::tx_extra_nonce, cryptonote::tx_extra_merge_mining_tag, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>, _Alloc = std::allocator<boost::variant<cryptonote::tx_extra_padding, cryptonote::tx_extra_pub_key, cryptonote::tx_extra_nonce, cryptonote::tx_extra_merge_mining_tag, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> >](), tx_extra_fields->std::vector<_Tp, _Alloc>::end [with _Tp = boost::variant<cryptonote::tx_extra_padding, cryptonote::tx_extra_pub_key, cryptonote::tx_extra_nonce, cryptonote::tx_extra_merge_mining_tag, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>, _Alloc = std::allocator<boost::variant<cryptonote::tx_extra_padding, cryptonote::tx_extra_pub_key, cryptonote::tx_extra_nonce, cryptonote::tx_extra_merge_mining_tag, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> >](), <expression error>)’
../src/main.cc: At global scope:
../src/main.cc:20: error: expected constructor, destructor, or type conversion before ‘<’ token
../src/main.cc:80: error: expected constructor, destructor, or type conversion before ‘<’ token
../src/main.cc:51: warning: ‘bool mergeBlocks(const cryptonote::block&, cryptonote::block&, const std::vector<crypto::hash, std::allocator<crypto::hash> >&)’ defined but not used
../src/main.cc:68: warning: ‘bool construct_parent_block(const cryptonote::block&, cryptonote::block&)’ defined but not used
make: *** [Release/obj.target/cryptonote/src/main.o] Error 1
make: Leaving directory `/home/intense/pool/node_modules/cryptonote-util/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 2.6.32-696.3.2.el6.x86_64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/intense/pool/node_modules/cryptonote-util
gyp ERR! node -v v6.11.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
cryptonote-universal-pool@0.0.1 /home/intense/pool
└── multi-hashing@0.0.9  (git://github.com/fancoder/node-multi-hashing.git#ec00b7429b668b3366d80a8fa85e9c22b4792d70)

npm ERR! Linux 2.6.32-696.3.2.el6.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "update"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! cryptonote-util@0.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cryptonote-util@0.0.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the cryptonote-util package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs cryptonote-util
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls cryptonote-util
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/intense/pool/npm-debug.log
```

```
[intense@server1 pool]$ npm owner ls cryptonote-util
npm ERR! owner ls Couldn't get owner data cryptonote-util
npm ERR! Linux 2.6.32-696.3.2.el6.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "owner" "ls" "cryptonote-util"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/cryptonote-util
npm ERR! 404
npm ERR! 404  'cryptonote-util' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/intense/pool/npm-debug.log
[intense@server1 pool]$ npm bugs cryptonote-util
npm ERR! Linux 2.6.32-696.3.2.el6.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "bugs" "cryptonote-util"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/cryptonote-util
npm ERR! 404
npm ERR! 404  'cryptonote-util' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/intense/pool/npm-debug.log
```

**Comment by alexshares** [comment]
Seeing the same. Sad to see such an awesome project fall apart. anyone have a working build?

**Comment by valiant1x** [comment]
Issue was resolved by downgrading nodejs version. I had success with both 0.10.x and 0.12.x

**Comment by Raspination** [comment]
@valiant1x  it worked for me only with 0.10

**Comment by PCPisChill** [comment]
@valiant1x 0.10 and 0.12 both fail for me
