### ISSUE TITLE
npm update Electroneum pool ERROR

### ISSUE THREAD

**Issue by icsugti** [fancoder/cryptonote-universal-pool#63]
I ve got this error:

```
C:\pool\node_modules\cryptonote-util>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_module
s\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\pool\node_modules\cryptonote-util\build\cryptonote.vcxproj(20,3): error MSB4019: The imported project "C:\Microsoft.
Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exist
s on disk.
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\buil
d.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_m
odules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\pool\node_modules\cryptonote-util
gyp ERR! node -v v8.7.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cryptonote-util@0.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cryptonote-util@0.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Charlie\AppData\Roaming\npm-cache\_logs\2017-11-05T05_38_28_595Z-debug.log
PS C:\pool>
```

**Comment by ghost** [comment]
Exactly the same problem here with the oficial crypto pool..tried with node 0.10.48 and 0.10.25

**Comment by minitzi** [comment]
hello. how did you manage to build electroneum ? 
Im getting this error : 
[ 58%] Building CXX object tests/core_tests/CMakeFiles/coretests.dir/block_validation.cpp.o
/root/electroneum-master/tests/core_tests/block_validation.cpp: In function 'bool {anonymous}::lift_up_difficulty(std::vector<boost::variant<cryptonote::block, cryptonote::transaction, cryptonote::account_base, callback_entry, serialized_object<cryptonote::block>, serialized_object<cryptonote::transaction>, event_visitor_settings> >&, std::vector<long unsigned int>&, std::vector<long unsigned int>&, test_generator&, size_t, cryptonote::block, const cryptonote::account_base&)':
/root/electroneum-master/tests/core_tests/block_validation.cpp:48:85: error: 'DIFFICULTY_TARGET_V1' was not declared in this scope
       difficulty_type diffic = next_difficulty(timestamps, cummulative_difficulties,DIFFICULTY_TARGET_V1);
                                                                                     ^
/root/electroneum-master/tests/core_tests/block_validation.cpp: In member function 'bool gen_block_invalid_nonce::generate(std::vector<boost::variant<cryptonote::block, cryptonote::transaction, cryptonote::account_base, callback_entry, serialized_object<cryptonote::block>, serialized_object<cryptonote::transaction>, event_visitor_settings> >&) const':
/root/electroneum-master/tests/core_tests/block_validation.cpp:178:81: error: 'DIFFICULTY_TARGET_V1' was not declared in this scope
   difficulty_type diffic = next_difficulty(timestamps, commulative_difficulties,DIFFICULTY_TARGET_V1);
                                                                                 ^
In file included from /root/electroneum-master/src/cryptonote_basic/cryptonote_basic.h:47:0,
                 from /root/electroneum-master/src/cryptonote_basic/account.h:33,
                 from /root/electroneum-master/src/cryptonote_basic/account_boost_serialization.h:33,
                 from /root/electroneum-master/tests/core_tests/chaingen.h:47,
                 from /root/electroneum-master/tests/core_tests/block_validation.cpp:31:
/root/electroneum-master/tests/core_tests/block_validation.cpp: In member function 'bool gen_block_unlock_time_is_timestamp_in_future::generate(std::vector<boost::variant<cryptonote::block, cryptonote::transaction, cryptonote::account_base, callback_entry, serialized_object<cryptonote::block>, serialized_object<cryptonote::transaction>, event_visitor_settings> >&) const':
/root/electroneum-master/src/cryptonote_config.h:85:57: error: 'DIFFICULTY_TARGET_V1' was not declared in this scope
 #define DIFFICULTY_BLOCKS_ESTIMATE_TIMESPAN             DIFFICULTY_TARGET_V1 //just alias; used by tests
                                                         ^
/root/electroneum-master/tests/core_tests/block_validation.cpp:267:87: note: in expansion of macro 'DIFFICULTY_BLOCKS_ESTIMATE_TIMESPAN'
   miner_tx.unlock_time = blk_0.timestamp + 3 * CRYPTONOTE_MINED_MONEY_UNLOCK_WINDOW * DIFFICULTY_BLOCKS_ESTIMATE_TIMESPAN;
                                                                                       ^
/root/electroneum-master/tests/core_tests/block_validation.cpp: In member function 'bool gen_block_invalid_binary_format::generate(std::vector<boost::variant<cryptonote::block, crypton


using Ubuntu 16.04.3 LTS \n \l
Thanks

**Comment by wanda7566** [comment]
delete node_modules directory, install 0.10.25 node, then run npm update

**Comment by PCPisChill** [comment]
@p1vynodejs Doesn't fix it
