### ISSUE TITLE
Build instructions have so many holes

### ISSUE THREAD

**Issue by gaylordbendylover** [fancoder/cryptonote-universal-pool#76]
I have wasted so much time trying to follow the installation instructions.  i've re-installed like 13 times, 2 different ubuntu distros and i keep running into the same issues repeatedly:  'npm update' (npm v5.6.0 on nodejs v9.3.0) doesn't bring in all the modules.  Bignum doesn't usually install , but sometimes it does, (weird to me),  multi-hashing doesn't install ever, cryptonote-utils doesn't install ever.  Can anyone please help me (with this issue, other issues probably not lol) ??

Heres the huge error output when running "npm update" :

noder@ubuntu:~/pool$ npm update

> cryptonote-util@0.0.1 install /home/noder/pool/node_modules/cryptonote-util
> node-gyp rebuild

make: Entering directory '/home/noder/pool/node_modules/cryptonote-util/build'
  CXX(target) Release/obj.target/cryptonote/src/main.o
../src/main.cc: In function ‘v8::Handle<v8::Value> except(const char*)’:
../src/main.cc:21:44: error: ‘New’ is not a member of ‘v8::String’
     return ThrowException(Exception::Error(String::New(msg)));
                                            ^
../src/main.cc:21:61: error: ‘ThrowException’ was not declared in this scope
     return ThrowException(Exception::Error(String::New(msg)));
                                                             ^
../src/main.cc: At global scope:
../src/main.cc:80:34: error: ‘Arguments’ does not name a type
 Handle<Value> convert_blob(const Arguments& args) {
                                  ^
In file included from /home/noder/.node-gyp/9.3.0/include/node/node.h:63:0,
                 from ../src/main.cc:2:
/home/noder/.node-gyp/9.3.0/include/node/v8.h: In function ‘v8::Handle<v8::Value> convert_blob(const int&)’:
/home/noder/.node-gyp/9.3.0/include/node/v8.h:875:13: error: ‘v8::HandleScope::HandleScope()’ is protected
   V8_INLINE HandleScope() {}
             ^
../src/main.cc:81:17: error: within this context
     HandleScope scope;
                 ^
../src/main.cc:83:14: error: request for member ‘Length’ in ‘args’, which is of non-class type ‘const int’
     if (args.Length() < 1)
              ^
../src/main.cc:86:34: error: invalid types ‘const int[int]’ for array subscript
     Local<Object> target = args[0]->ToObject();
                                  ^
../src/main.cc:111:11: error: expected primary-expression before ‘*’ token
     Buffer* buff = Buffer::New(output.data(), output.size());
           ^
../src/main.cc:111:13: error: ‘buff’ was not declared in this scope
     Buffer* buff = Buffer::New(output.data(), output.size());
             ^
../src/main.cc:111:60: error: no matching function for call to ‘New(const char*, std::__cxx11::basic_string<char>::size_type)’
     Buffer* buff = Buffer::New(output.data(), output.size());
                                                            ^
In file included from ../src/main.cc:3:0:
/home/noder/.node-gyp/9.3.0/include/node/node_buffer.h:52:40: note: candidate: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, size_t)
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate, size_t length);
                                        ^
/home/noder/.node-gyp/9.3.0/include/node/node_buffer.h:52:40: note:   no known conversion for argument 1 from ‘const char*’ to ‘v8::Isolate*’
/home/noder/.node-gyp/9.3.0/include/node/node_buffer.h:55:40: note: candidate: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding)
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/noder/.node-gyp/9.3.0/include/node/node_buffer.h:55:40: note:   no known conversion for argument 1 from ‘const char*’ to ‘v8::Isolate*’
/home/noder/.node-gyp/9.3.0/include/node/node_buffer.h:60:40: note: candidate: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t, node::Buffer::FreeCallback, void*)
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/noder/.node-gyp/9.3.0/include/node/node_buffer.h:60:40: note:   candidate expects 5 arguments, 2 provided
/home/noder/.node-gyp/9.3.0/include/node/node_buffer.h:67:40: note: candidate: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t)
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/noder/.node-gyp/9.3.0/include/node/node_buffer.h:67:40: note:   candidate expects 3 arguments, 2 provided
../src/main.cc:112:18: error: ‘class v8::HandleScope’ has no member named ‘Close’
     return scope.Close(buff->handle_);
                  ^
../src/main.cc: At global scope:
../src/main.cc:115:34: error: ‘Arguments’ does not name a type
 Handle<Value> get_block_id(const Arguments& args) {
                                  ^
In file included from /home/noder/.node-gyp/9.3.0/include/node/node.h:63:0,
                 from ../src/main.cc:2:
/home/noder/.node-gyp/9.3.0/include/node/v8.h: In function ‘v8::Handle<v8::Value> get_block_id(const int&)’:
/home/noder/.node-gyp/9.3.0/include/node/v8.h:875:13: error: ‘v8::HandleScope::HandleScope()’ is protected
   V8_INLINE HandleScope() {}
             ^
../src/main.cc:116:17: error: within this context
     HandleScope scope;
                 ^
../src/main.cc:118:14: error: request for member ‘Length’ in ‘args’, which is of non-class type ‘const int’
     if (args.Length() < 1)
              ^
../src/main.cc:121:34: error: invalid types ‘const int[int]’ for array subscript
     Local<Object> target = args[0]->ToObject();
                                  ^
../src/main.cc:137:11: error: expected primary-expression before ‘*’ token
     Buffer* buff = Buffer::New(reinterpret_cast<char*>(&block_id), sizeof(block_id));
           ^
../src/main.cc:137:13: error: ‘buff’ was not declared in this scope
     Buffer* buff = Buffer::New(reinterpret_cast<char*>(&block_id), sizeof(block_id));
             ^
../src/main.cc:137:84: error: no matching function for call to ‘New(char*, long unsigned int)’
     Buffer* buff = Buffer::New(reinterpret_cast<char*>(&block_id), sizeof(block_id));
                                                                                    ^
In file included from ../src/main.cc:3:0:
/home/noder/.node-gyp/9.3.0/include/node/node_buffer.h:52:40: note: candidate: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, size_t)
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate, size_t length);
                                        ^
/home/noder/.node-gyp/9.3.0/include/node/node_buffer.h:52:40: note:   no known conversion for argument 1 from ‘char*’ to ‘v8::Isolate*’
/home/noder/.node-gyp/9.3.0/include/node/node_buffer.h:55:40: note: candidate: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding)
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/noder/.node-gyp/9.3.0/include/node/node_buffer.h:55:40: note:   no known conversion for argument 1 from ‘char*’ to ‘v8::Isolate*’
/home/noder/.node-gyp/9.3.0/include/node/node_buffer.h:60:40: note: candidate: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t, node::Buffer::FreeCallback, void*)
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/noder/.node-gyp/9.3.0/include/node/node_buffer.h:60:40: note:   candidate expects 5 arguments, 2 provided
/home/noder/.node-gyp/9.3.0/include/node/node_buffer.h:67:40: note: candidate: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t)
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/noder/.node-gyp/9.3.0/include/node/node_buffer.h:67:40: note:   candidate expects 3 arguments, 2 provided
../src/main.cc:138:18: error: ‘class v8::HandleScope’ has no member named ‘Close’
     return scope.Close(buff->handle_);
                  ^
../src/main.cc: At global scope:
../src/main.cc:141:42: error: ‘Arguments’ does not name a type
 Handle<Value> construct_block_blob(const Arguments& args) {
                                          ^
In file included from /home/noder/.node-gyp/9.3.0/include/node/node.h:63:0,
                 from ../src/main.cc:2:
/home/noder/.node-gyp/9.3.0/include/node/v8.h: In function ‘v8::Handle<v8::Value> construct_block_blob(const int&)’:
/home/noder/.node-gyp/9.3.0/include/node/v8.h:875:13: error: ‘v8::HandleScope::HandleScope()’ is protected
   V8_INLINE HandleScope() {}
             ^
../src/main.cc:142:17: error: within this context
     HandleScope scope;
                 ^
../src/main.cc:144:14: error: request for member ‘Length’ in ‘args’, which is of non-class type ‘const int’
     if (args.Length() < 2)
              ^
../src/main.cc:147:46: error: invalid types ‘const int[int]’ for array subscript
     Local<Object> block_template_buf = args[0]->ToObject();
                                              ^
../src/main.cc:148:37: error: invalid types ‘const int[int]’ for array subscript
     Local<Object> nonce_buf = args[1]->ToObject();
                                     ^
../src/main.cc:179:11: error: expected primary-expression before ‘*’ token
     Buffer* buff = Buffer::New(output.data(), output.size());
           ^
../src/main.cc:179:13: error: ‘buff’ was not declared in this scope
     Buffer* buff = Buffer::New(output.data(), output.size());
             ^
../src/main.cc:179:60: error: no matching function for call to ‘New(const char*, std::__cxx11::basic_string<char>::size_type)’
     Buffer* buff = Buffer::New(output.data(), output.size());
                                                            ^
In file included from ../src/main.cc:3:0:
/home/noder/.node-gyp/9.3.0/include/node/node_buffer.h:52:40: note: candidate: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, size_t)
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate, size_t length);
                                        ^
/home/noder/.node-gyp/9.3.0/include/node/node_buffer.h:52:40: note:   no known conversion for argument 1 from ‘const char*’ to ‘v8::Isolate*’
/home/noder/.node-gyp/9.3.0/include/node/node_buffer.h:55:40: note: candidate: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding)
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/noder/.node-gyp/9.3.0/include/node/node_buffer.h:55:40: note:   no known conversion for argument 1 from ‘const char*’ to ‘v8::Isolate*’
/home/noder/.node-gyp/9.3.0/include/node/node_buffer.h:60:40: note: candidate: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t, node::Buffer::FreeCallback, void*)
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/noder/.node-gyp/9.3.0/include/node/node_buffer.h:60:40: note:   candidate expects 5 arguments, 2 provided
/home/noder/.node-gyp/9.3.0/include/node/node_buffer.h:67:40: note: candidate: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t)
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/noder/.node-gyp/9.3.0/include/node/node_buffer.h:67:40: note:   candidate expects 3 arguments, 2 provided
../src/main.cc:180:18: error: ‘class v8::HandleScope’ has no member named ‘Close’
     return scope.Close(buff->handle_);
                  ^
../src/main.cc: At global scope:
../src/main.cc:183:37: error: ‘Arguments’ does not name a type
 Handle<Value> convert_blob_bb(const Arguments& args) {
                                     ^
In file included from /home/noder/.node-gyp/9.3.0/include/node/node.h:63:0,
                 from ../src/main.cc:2:
/home/noder/.node-gyp/9.3.0/include/node/v8.h: In function ‘v8::Handle<v8::Value> convert_blob_bb(const int&)’:
/home/noder/.node-gyp/9.3.0/include/node/v8.h:875:13: error: ‘v8::HandleScope::HandleScope()’ is protected
   V8_INLINE HandleScope() {}
             ^
../src/main.cc:184:17: error: within this context
     HandleScope scope;
                 ^
../src/main.cc:186:14: error: request for member ‘Length’ in ‘args’, which is of non-class type ‘const int’
     if (args.Length() < 1)
              ^
../src/main.cc:189:34: error: invalid types ‘const int[int]’ for array subscript
     Local<Object> target = args[0]->ToObject();
                                  ^
../src/main.cc:204:11: error: expected primary-expression before ‘*’ token
     Buffer* buff = Buffer::New(output.data(), output.size());
           ^
../src/main.cc:204:13: error: ‘buff’ was not declared in this scope
     Buffer* buff = Buffer::New(output.data(), output.size());
             ^
../src/main.cc:204:60: error: no matching function for call to ‘New(const char*, std::__cxx11::basic_string<char>::size_type)’
     Buffer* buff = Buffer::New(output.data(), output.size());
                                                            ^
In file included from ../src/main.cc:3:0:
/home/noder/.node-gyp/9.3.0/include/node/node_buffer.h:52:40: note: candidate: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, size_t)
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate, size_t length);
                                        ^
/home/noder/.node-gyp/9.3.0/include/node/node_buffer.h:52:40: note:   no known conversion for argument 1 from ‘const char*’ to ‘v8::Isolate*’
/home/noder/.node-gyp/9.3.0/include/node/node_buffer.h:55:40: note: candidate: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding)
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/noder/.node-gyp/9.3.0/include/node/node_buffer.h:55:40: note:   no known conversion for argument 1 from ‘const char*’ to ‘v8::Isolate*’
/home/noder/.node-gyp/9.3.0/include/node/node_buffer.h:60:40: note: candidate: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t, node::Buffer::FreeCallback, void*)
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/noder/.node-gyp/9.3.0/include/node/node_buffer.h:60:40: note:   candidate expects 5 arguments, 2 provided
/home/noder/.node-gyp/9.3.0/include/node/node_buffer.h:67:40: note: candidate: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t)
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/noder/.node-gyp/9.3.0/include/node/node_buffer.h:67:40: note:   candidate expects 3 arguments, 2 provided
../src/main.cc:205:18: error: ‘class v8::HandleScope’ has no member named ‘Close’
     return scope.Close(buff->handle_);
                  ^
../src/main.cc: At global scope:
../src/main.cc:208:36: error: ‘Arguments’ does not name a type
 Handle<Value> address_decode(const Arguments& args) {
                                    ^
In file included from /home/noder/.node-gyp/9.3.0/include/node/node.h:63:0,
                 from ../src/main.cc:2:
/home/noder/.node-gyp/9.3.0/include/node/v8.h: In function ‘v8::Handle<v8::Value> address_decode(const int&)’:
/home/noder/.node-gyp/9.3.0/include/node/v8.h:875:13: error: ‘v8::HandleScope::HandleScope()’ is protected
   V8_INLINE HandleScope() {}
             ^
../src/main.cc:209:17: error: within this context
     HandleScope scope;
                 ^
../src/main.cc:211:14: error: request for member ‘Length’ in ‘args’, which is of non-class type ‘const int’
     if (args.Length() < 1)
              ^
../src/main.cc:214:34: error: invalid types ‘const int[int]’ for array subscript
     Local<Object> target = args[0]->ToObject();
                                  ^
../src/main.cc:224:22: error: ‘class v8::HandleScope’ has no member named ‘Close’
         return scope.Close(Undefined());
                      ^
../src/main.cc:224:38: error: too few arguments to function ‘v8::Local<v8::Primitive> v8::Undefined(v8::Isolate*)’
         return scope.Close(Undefined());
                                      ^
In file included from /home/noder/.node-gyp/9.3.0/include/node/node.h:63:0,
                 from ../src/main.cc:2:
/home/noder/.node-gyp/9.3.0/include/node/v8.h:313:27: note: declared here
   friend Local<Primitive> Undefined(Isolate* isolate);
                           ^
../src/main.cc:228:22: error: ‘class v8::HandleScope’ has no member named ‘Close’
         return scope.Close(Undefined());
                      ^
../src/main.cc:228:38: error: too few arguments to function ‘v8::Local<v8::Primitive> v8::Undefined(v8::Isolate*)’
         return scope.Close(Undefined());
                                      ^
In file included from /home/noder/.node-gyp/9.3.0/include/node/node.h:63:0,
                 from ../src/main.cc:2:
/home/noder/.node-gyp/9.3.0/include/node/v8.h:313:27: note: declared here
   friend Local<Primitive> Undefined(Isolate* isolate);
                           ^
../src/main.cc:231:22: error: ‘class v8::HandleScope’ has no member named ‘Close’
         return scope.Close(Undefined());
                      ^
../src/main.cc:231:38: error: too few arguments to function ‘v8::Local<v8::Primitive> v8::Undefined(v8::Isolate*)’
         return scope.Close(Undefined());
                                      ^
In file included from /home/noder/.node-gyp/9.3.0/include/node/node.h:63:0,
                 from ../src/main.cc:2:
/home/noder/.node-gyp/9.3.0/include/node/v8.h:313:27: note: declared here
   friend Local<Primitive> Undefined(Isolate* isolate);
                           ^
../src/main.cc:233:18: error: ‘class v8::HandleScope’ has no member named ‘Close’
     return scope.Close(Integer::New(static_cast<uint32_t>(prefix)));
                  ^
../src/main.cc:233:66: error: no matching function for call to ‘v8::Integer::New(uint32_t)’
     return scope.Close(Integer::New(static_cast<uint32_t>(prefix)));
                                                                  ^
In file included from /home/noder/.node-gyp/9.3.0/include/node/node.h:63:0,
                 from ../src/main.cc:2:
/home/noder/.node-gyp/9.3.0/include/node/v8.h:2929:25: note: candidate: static v8::Local<v8::Integer> v8::Integer::New(v8::Isolate*, int32_t)
   static Local<Integer> New(Isolate* isolate, int32_t value);
                         ^
/home/noder/.node-gyp/9.3.0/include/node/v8.h:2929:25: note:   candidate expects 2 arguments, 1 provided
../src/main.cc: In function ‘void init(v8::Handle<v8::Object>)’:
../src/main.cc:237:18: error: ‘NewSymbol’ is not a member of ‘v8::String’
     exports->Set(String::NewSymbol("construct_block_blob"), FunctionTemplate::New(construct_block_blob)->GetFunction());
                  ^
../src/main.cc:237:103: error: no matching function for call to ‘v8::FunctionTemplate::New(v8::Handle<v8::Value> (&)(const int&))’
     exports->Set(String::NewSymbol("construct_block_blob"), FunctionTemplate::New(construct_block_blob)->GetFunction());
                                                                                                       ^
In file included from /home/noder/.node-gyp/9.3.0/include/node/node.h:63:0,
                 from ../src/main.cc:2:
/home/noder/.node-gyp/9.3.0/include/node/v8.h:5475:34: note: candidate: static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::Isolate*, v8::FunctionCallback, v8::Local<v8::Value>, v8::Local<v8::Signature>, int, v8::ConstructorBehavior)
   static Local<FunctionTemplate> New(
                                  ^
/home/noder/.node-gyp/9.3.0/include/node/v8.h:5475:34: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>(const int&) {aka v8::Local<v8::Value>(const int&)}’ to ‘v8::Isolate*’
../src/main.cc:238:18: error: ‘NewSymbol’ is not a member of ‘v8::String’
     exports->Set(String::NewSymbol("get_block_id"), FunctionTemplate::New(get_block_id)->GetFunction());
                  ^
../src/main.cc:238:87: error: no matching function for call to ‘v8::FunctionTemplate::New(v8::Handle<v8::Value> (&)(const int&))’
     exports->Set(String::NewSymbol("get_block_id"), FunctionTemplate::New(get_block_id)->GetFunction());
                                                                                       ^
In file included from /home/noder/.node-gyp/9.3.0/include/node/node.h:63:0,
                 from ../src/main.cc:2:
/home/noder/.node-gyp/9.3.0/include/node/v8.h:5475:34: note: candidate: static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::Isolate*, v8::FunctionCallback, v8::Local<v8::Value>, v8::Local<v8::Signature>, int, v8::ConstructorBehavior)
   static Local<FunctionTemplate> New(
                                  ^
/home/noder/.node-gyp/9.3.0/include/node/v8.h:5475:34: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>(const int&) {aka v8::Local<v8::Value>(const int&)}’ to ‘v8::Isolate*’
../src/main.cc:239:18: error: ‘NewSymbol’ is not a member of ‘v8::String’
     exports->Set(String::NewSymbol("convert_blob"), FunctionTemplate::New(convert_blob)->GetFunction());
                  ^
../src/main.cc:239:87: error: no matching function for call to ‘v8::FunctionTemplate::New(v8::Handle<v8::Value> (&)(const int&))’
     exports->Set(String::NewSymbol("convert_blob"), FunctionTemplate::New(convert_blob)->GetFunction());
                                                                                       ^
In file included from /home/noder/.node-gyp/9.3.0/include/node/node.h:63:0,
                 from ../src/main.cc:2:
/home/noder/.node-gyp/9.3.0/include/node/v8.h:5475:34: note: candidate: static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::Isolate*, v8::FunctionCallback, v8::Local<v8::Value>, v8::Local<v8::Signature>, int, v8::ConstructorBehavior)
   static Local<FunctionTemplate> New(
                                  ^
/home/noder/.node-gyp/9.3.0/include/node/v8.h:5475:34: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>(const int&) {aka v8::Local<v8::Value>(const int&)}’ to ‘v8::Isolate*’
../src/main.cc:240:18: error: ‘NewSymbol’ is not a member of ‘v8::String’
     exports->Set(String::NewSymbol("convert_blob_bb"), FunctionTemplate::New(convert_blob_bb)->GetFunction());
                  ^
../src/main.cc:240:93: error: no matching function for call to ‘v8::FunctionTemplate::New(v8::Handle<v8::Value> (&)(const int&))’
     exports->Set(String::NewSymbol("convert_blob_bb"), FunctionTemplate::New(convert_blob_bb)->GetFunction());
                                                                                             ^
In file included from /home/noder/.node-gyp/9.3.0/include/node/node.h:63:0,
                 from ../src/main.cc:2:
/home/noder/.node-gyp/9.3.0/include/node/v8.h:5475:34: note: candidate: static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::Isolate*, v8::FunctionCallback, v8::Local<v8::Value>, v8::Local<v8::Signature>, int, v8::ConstructorBehavior)
   static Local<FunctionTemplate> New(
                                  ^
/home/noder/.node-gyp/9.3.0/include/node/v8.h:5475:34: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>(const int&) {aka v8::Local<v8::Value>(const int&)}’ to ‘v8::Isolate*’
../src/main.cc:241:18: error: ‘NewSymbol’ is not a member of ‘v8::String’
     exports->Set(String::NewSymbol("address_decode"), FunctionTemplate::New(address_decode)->GetFunction());
                  ^
../src/main.cc:241:91: error: no matching function for call to ‘v8::FunctionTemplate::New(v8::Handle<v8::Value> (&)(const int&))’
     exports->Set(String::NewSymbol("address_decode"), FunctionTemplate::New(address_decode)->GetFunction());
                                                                                           ^
In file included from /home/noder/.node-gyp/9.3.0/include/node/node.h:63:0,
                 from ../src/main.cc:2:
/home/noder/.node-gyp/9.3.0/include/node/v8.h:5475:34: note: candidate: static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::Isolate*, v8::FunctionCallback, v8::Local<v8::Value>, v8::Local<v8::Signature>, int, v8::ConstructorBehavior)
   static Local<FunctionTemplate> New(
                                  ^
/home/noder/.node-gyp/9.3.0/include/node/v8.h:5475:34: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>(const int&) {aka v8::Local<v8::Value>(const int&)}’ to ‘v8::Isolate*’
cryptonote.target.mk:107: recipe for target 'Release/obj.target/cryptonote/src/main.o' failed
make: *** [Release/obj.target/cryptonote/src/main.o] Error 1
make: Leaving directory '/home/noder/pool/node_modules/cryptonote-util/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:159:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Linux 4.4.0-104-generic
gyp ERR! command "/usr/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/noder/pool/node_modules/cryptonote-util
gyp ERR! node -v v9.3.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cryptonote-util@0.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cryptonote-util@0.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/noder/.npm/_logs/2017-12-20T18_40_09_570Z-debug.log

**Comment by Daxorinator** [comment]
Getting the exact same error, what is this and why is it happening?

**Comment by gaylordbendylover** [comment]
I found an answer to this somewhere else, but i'll paste it here too:
First remove NodeJS that you already installed:
$sudo ap-get remove npm nodejs -y

Then download and unzip NodeJS v0.10.25
$wget https://nodejs.org/dist/v0.10.25/node-v0.10.25.tar.gz && tar xvzf node-v0.10.25.tar.gz

Compile and Install NodeJS and NPM from the source:
$cd node-v0.10.25
$make
$sudo make install

Make sure to remove node_modules directory:
$cd /home/user/pool
$sudo rm -r node_modules

run npm update:
$npm update

that fixed it for me.  i hope it does for you too.

**Comment by eightsixeight** [comment]
use sudo
sudo npm update 

etc

**Comment by antstalepresh** [comment]
@gaylordbendylover, thanks for your answer, took long time but successed!!!

**Comment by Daveiano** [comment]
NodeJS [v0.10.25](https://nodejs.org/en/blog/release/v0.10.25/) is from 2014-01-23, is this not going to work with a current version?
