### ISSUE TITLE
can't startup application

### ISSUE THREAD

**Issue by nskuijpers** [fancoder/cryptonote-universal-pool#90]
master] Pool fork 1 died, spawning replacement worker...
/home/pool/pool/node_modules/bindings/bindings.js:96
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → /home/pool/pool/node_modules/multi-hashing/build/multihashing.node
 → /home/pool/pool/node_modules/multi-hashing/build/Debug/multihashing.node
 → /home/pool/pool/node_modules/multi-hashing/build/Release/multihashing.node
 → /home/pool/pool/node_modules/multi-hashing/out/Debug/multihashing.node
 → /home/pool/pool/node_modules/multi-hashing/Debug/multihashing.node
 → /home/pool/pool/node_modules/multi-hashing/out/Release/multihashing.node
 → /home/pool/pool/node_modules/multi-hashing/Release/multihashing.node
 → /home/pool/pool/node_modules/multi-hashing/build/default/multihashing.node
 → /home/pool/pool/node_modules/multi-hashing/compiled/4.2.6/linux/x64/multihashing.node
    at bindings (/home/pool/pool/node_modules/bindings/bindings.js:93:9)
    at Object.<anonymous> (/home/pool/pool/node_modules/multi-hashing/index.js:1:99)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/pool/pool/lib/pool.js:7:20)
    at Module._compile (module.js:410:26)

**Comment by spectre-knight** [comment]
node version ??
`$ node -v`

**Comment by LoganOneal** [comment]
+1

**Comment by nskuijpers** [comment]
Sorry already fixed it
Version v0.25

**Comment by LoganOneal** [comment]
How did you fix it?

**Comment by nskuijpers** [comment]
I used nvm to install version v0.10.25 and upgrade the server to 2 cpu and 4gb and run npm update and it works
