### ISSUE TITLE
Syntax Error: Unexpected String 

### ISSUE THREAD

**Issue by 420coupe** [fancoder/cryptonote-universal-pool#91]
I am running into the following issue when running the command below. 

Currently running Ubuntu 14.04 LTS

I've tried a fresh install and fresh instance of ubuntu 14.04 with fresh install of all requirements, and still run into the same issue. 

Any assistance would greatly be appreciated. 

sudo node init.js
SyntaxError: Unexpected string

/home/ubuntu/pool/lib/logger.js:16
var logDir = config.logging.files.directory;
             ^
ReferenceError: config is not defined
    at Object.<anonymous> (/home/ubuntu/pool/lib/logger.js:16:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/ubuntu/pool/init.js:10:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)

**Comment by spectre-knight** [comment]
node version ??? 

`$ node -v `

**Comment by shinystat** [comment]
I have the same error
my node version is v0.10.25
Thanks for the support

**Comment by maurosbicego** [comment]
It's because there is a string that shouldn't be...
I think you should use another config.json

**Comment by swanseahost** [comment]
How to fix please ? 

cryptonote-solacecoin-pool/lib/logger.js:16
var logDir = config.logging.files.directory;

**Comment by milaas** [comment]
same problem how to fix
