### ISSUE TITLE
Charts not updating

### ISSUE THREAD

**Issue by leisegang** [fancoder/cryptonote-universal-pool#99]
Before after a restart the charts_info.log had this after start:

```
2018-01-29 00:27:11 Started
2018-01-29 00:28:11 hashrate chart collected value 69734. Total sets count 26
2018-01-29 00:28:11 workers chart collected value 55. Total sets count 26
2018-01-29 00:29:11 hashrate chart collected value 70867. Total sets count 26
2018-01-29 00:29:11 workers chart collected value 55. Total sets count 26
```

now when i start it just says started:

```
2018-01-29 00:43:10 Started
2018-01-29 00:50:13 Started
2018-01-29 17:55:27 Started
2018-01-29 19:34:55 Started
2018-01-31 11:38:23 Started
2018-01-31 11:40:36 Started
2018-01-31 11:46:46 Started
2018-01-31 11:48:54 Started
2018-01-31 12:05:20 Started
2018-01-31 12:06:59 Started
2018-01-31 12:08:26 Started
2018-01-31 13:50:03 Started
2018-01-31 13:52:44 Started
2018-01-31 13:58:51 Started
2018-01-31 14:04:35 Started
2018-01-31 14:10:25 Started
2018-01-31 14:14:12 Started
2018-01-31 20:50:26 Started
```

i have no charts other than payment being updated. 

API writes this to the logs/terminal:

`[api] Stat collection finished: 2 ms redis, 4 ms daemon`

i can not see anything like this in my tail -f *.log
```
2017-07-12 16:43:42 [charts] Started
2017-07-12 16:43:42 [chartsDataCollector] Started
```

```
2018-01-28 23:56:02
TypeError: Cannot read property 'error' of undefined
    at /dinasty/pool/lib/charts.js:188:26
    at IncomingMessage.<anonymous> (/dinasty/pool/lib/apiInterfaces.js:31:17)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)
chartsDataCollector_crash.log
```

i am running the forknote-pool fork "default" no edits

when i look in the url:port/stats the chart data is OLD but the other data is NEW.

**Comment by Warlordas** [comment]
Sorry for hijacking, but i have a similar problem. I only get Hashrate and workers charts showing up, but difficulty and other charts won't show up.

The charts_info.log shows only hashrate and workers updating too. 
2018-02-03 08:19:30 Started
2018-02-03 08:19:30 Started
2018-02-03 08:20:30 hashrate chart collected value 0. Total sets count 1
2018-02-03 08:20:30 workers chart collected value 0. Total sets count 

Would appreciate any help

**Comment by CerveloFellow** [comment]
Check your website/config.js and make sure the api call back is set correctly to your host or ip address and port.  Make sure youv'e got that port open as well and not firewalled.  Try to navigate to http://ip:port and see if you get something like "Invalid API call" just to make sure that's even running on the right port and open.
